services:
  db:
    image: postgres:16-alpine
    container_name: simons_pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-simons_db}
      POSTGRES_USER: ${POSTGRES_USER:-simons}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-simons} -d ${POSTGRES_DB:-simons_db} -q"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
