# Generated by Django 5.2.7 on 2025-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='nucleotide', max_length=64)),
                ('accession_id', models.CharField(db_index=True, max_length=64)),
                ('rettype', models.CharField(default='fasta', max_length=32)),
                ('retmode', models.CharField(default='xml', max_length=32)),
                ('content', models.TextField()),
                ('content_length', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['accession_id', 'db'], name='nucleotides_accessi_6c932a_idx')],
                'unique_together': {('db', 'accession_id', 'rettype', 'retmode')},
            },
        ),
    ]
